name: Deploy static content to GitHub Pages

on:
  push:
    tags:
      - "*"
    branches:
      - "main"
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages

env:
  BUILD_PATH: "./src/BlazorWebApp"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Restore WebAssembly tools
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore ${{ env.BUILD_PATH }}

      - name: Build
        run: dotnet publish ${{ env.BUILD_PATH }} --configuration Release --output publish
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ env.BUILD_PATH }}/publish/wwwroot"

  deploy:
    name: Deploy
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
